version: '3'

services:
  redbooks-rag:
    build: .
    container_name: redbooks-rag
    volumes:
      - ./scripts:/app/scripts
      - ${PDF_PATH:-./data/pdfs}:/data/pdfs
      - ${PROCESSED_PATH:-./data/processed_redbooks}:/data/processed_redbooks
      - ${OPENWEBUI_PATH:-./data/openwebui}:/data/openwebui
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    ports:
      - "8000:8000"  # If you add a web interface in the future
    tty: true
    stdin_open: true

  ollama:
    image: ollama/ollama:latest
    container_name: redbooks-ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama_data:
