version: '3'

services:
  redbooks-rag:
    build: .
    container_name: redbooks-rag
    volumes:
      - ./scripts:/app/scripts:z
      - ./data/pdfs:/data/pdfs:z
      - ./data/processed_redbooks:/data/processed_redbooks:z
      - ./data/openwebui:/data/openwebui:z
    environment:
      - OLLAMA_BASE_URL=http://redbooks-ollama:11434
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true

  ollama:
    image: ollama/ollama:latest
    container_name: redbooks-ollama
    volumes:
      - ollama_data:/root/.ollama:z
    ports:
      - "11434:11434"

volumes:
  ollama_data:
